config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index]

  resources :accounts, only: [:new, :create, :edit, :update, :show, :destroy] do
    collection do
      get :manage_accounts
      get :bought_accounts
    end
  end

  resources :auctions, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
    resources :bids
    collection do
      get :manage_auctions
    end
    member do
      patch :start, :buy_immediately, :close
    end
  end

  get 'about', to: 'home#about'
  root to: 'home#index'

  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/auction.rb
class Auction < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :account
  has_many :bids

  enum status: [:created, :active, :finished, :closed]
  enum payment_type: [:immediate_pay, :half_pay, :end_period_pay]

  validates :payment_type, :final_price, :minimum_price, :end_date,
            presence: true
  validate :end_date_validation, :price_validation

  before_save do
    self.comission = calculate_comission
  end

  scope :active, -> { where(status: :active) }
  scope :make_closed, -> { where('end_date < ? and status = ?', Date.today - 24.hours, 'finished') }
  scope :yesterday, -> { where('end_date < ?', Date.today) }

  monetize :current_price_cents, numericality: { greater_than: 0 }
  monetize :minimum_price_cents, numericality: { greater_than: 0 }
  monetize :final_price_cents, numericality: { greater_than: 0 }

  PAYMENT_TYPES = { 'Pay immediately after auction end' => 'immediate_pay',
                    'Pay 50% immediately and 50% after 30 days' => 'half_pay',
                    'Pay 30 days after auction end' => 'end_period_pay' }.freeze

  aasm column: :status, enum: true, skip_validation_on_save: true do
    state :created, initial: true
    state :active, :finished, :closed

    event :start_auction do
      transitions from: :created, to: :active
    end

    event :finish_auction_event do
      transitions from: :active, to: :finished
    end

    event :close_auction_event do
      transitions from: :finished, to: :closed
    end
  end

  def close_auction
    close_auction_event!
    if bids.any?
      account.update_attributes(buyer_id: bids.last.user.id, status: :sold)
      bids.last.update_attributes(status: :final)
    else
      account.update_attributes(status: :opened)
    end
  end

  def finish_auction
    self.status = :finished
    save(validate: false)
  end

  def immediate_buy(user)
    return false if user.available_balance_with_auction(id) < final_price_cents
    bids.create(user_id: user.id, stake: final_price)
    finish_auction
  end

  def calculate_comission
    payment_type_multiplier = case payment_type
                              when 'immediate_pay'
                                2
                              when 'half_pay'
                                1.5
                              else
                                1
                              end
    Appvalues['auction_standard_commision'] * payment_type_multiplier
  end

  private

  def end_date_validation
    return unless end_date.present? && end_date < DateTime.now.tomorrow.to_date
    errors.add(:end_date, 'Auction end must be at least 24 hours from now')
  end

  def price_validation
    return unless final_price.present? && minimum_price.present? &&
                  minimum_price >= final_price
    errors.add(:minimum_price, 'Final price must be bigger than minimum price')
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :find_auction, only: [:show, :edit, :update, :destroy,
                                      :start, :buy_immediately, :close]
  before_action only: [:edit, :update, :destroy, :start] do
    check_status('created')
  end
  before_action only: [:close] do
    check_status('finished')
    check_user_access(@auction.bids.last.user)
  end
  before_action only: [:edit, :update, :destroy, :start] do
    check_user_access(@auction.user)
  end
  before_action :check_own_account, only: [:buy_immediately]
  skip_before_action :authenticate_user!, only: [:show, :index]

  def index
    @auctions = Auction.active.page(params[:page]).per(5)
  end

  def show
    check_user_access(@auction.user) if @auction.created?
    @bids = @auction.bids.last_bids
    @current_winner = @bids.any? && @bids.last.user == current_user
  end

  def new
    @auction = current_user.auctions.new
    @accounts = current_user.accounts.opened
    @selected_account_id = params[:selected_account] || @accounts.first.id
  end

  def create
    @auction = current_user.auctions.new(auction_params)
    @auction.current_price = @auction.minimum_price
    if @auction.save
      @auction.account.create_auction!
      redirect_to @auction, notice: 'Auction was created!'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    @auction.current_price = auction_params[:minimum_price]
    if @auction.update_attributes(auction_params)
      flash[:success] = 'Auction was succesfully updated'
      redirect_to @auction
    else
      render 'edit'
    end
  end

  def destroy
    @auction.destroy
    @auction.account.delete_auction!
    redirect_to manage_auctions_auctions_path, notice: 'Auction was deleted'
  end

  def manage_auctions
    @auctions = current_user.auctions
  end

  def start
    @auction.start_auction!
    redirect_back(fallback_location: root_path)
  end

  def buy_immediately
    if @auction.immediate_buy(current_user)
      redirect_to bought_accounts_accounts_path,
                  notice: 'You won the auction! You need to close auction
                           after seller sends you account details'
    else
      flash[:alert] = 'You have not enough money on
                        your balance to buy this account!'
      redirect_back(fallback_location: root_path)
    end
  end

  def close
    @auction.close_auction
    redirect_to bought_accounts_accounts_path,
                notice: 'Auction was closed! You have bought an account'
  end

  private

  def auction_params
    params.require(:auction).permit(:final_price, :minimum_price,
                                    :payment_type, :end_date, :account_id,
                                    :selected_account)
  end

  def find_auction
    @auction = Auction.find(params[:id])
  end

  def check_own_account
    return unless @auction.user == current_user
      flash[:alert] = 'You can not buy your own account!'
      redirect_back(fallback_location: root_path)
  end

  def check_status(status)
    return if @auction.status == status
    redirect_to manage_auctions_auctions_path,
                alert: 'You can not change auction'
  end

  def check_user_access(user)
    return if user == current_user
    flash[:alert] = 'Access denied!'
    redirect_back(fallback_location: root_path)
  end
end

app/views/auctions/_auction.html.slim
tr
  td= auction.account.user.name
  td= auction.account.bookmaker
  td= auction.account.age
  - if auction.account.own?
    td
      i.fa.fa-check-square-o
  - else
    td
      i.fa.fa-square-o
  td= auction.account.comment
  td
    - if current_user.present?
      = simple_form_for([auction, auction.bids.new], remote: true) do |f|
        = f.input_field :stake, label: false, value: auction.current_price,
                type: :number, min: auction.current_price, 'data-auction-id': auction.id
        = f.button :submit, class: 'btn-theme',
                  data: { confirm: 'Do you confirm the stake? This operation could not be canceled' }
    - else
      =  humanized_money_with_symbol auction.current_price
  td= link_to humanized_money_with_symbol(auction.final_price), buy_immediately_auction_path(auction),
          method: :patch,
          data: {confirm: "You will buy this account for #{humanized_money_with_symbol auction.final_price}. Confirm operation?"}
  td= Auction::PAYMENT_TYPES.key(auction.payment_type)
  td= date_formatter auction.end_date
  td= link_to auction do
    i.fa.fa-search

app/views/auctions/_manage.html.slim
- @auctions.each do |auction|
  tr
    td= time_formatter auction.created_at
    td= auction.account.to_s
    td= humanized_money_with_symbol auction.minimum_price
    td= humanized_money_with_symbol auction.current_price
    td= humanized_money_with_symbol auction.final_price
    td= Auction::PAYMENT_TYPES.key(auction.payment_type)
    td= date_formatter auction.end_date
    td= auction.comission
    td= link_to auction.status, auction_path(auction)
    - if auction.created?
      td= link_to 'Edit', edit_auction_path(auction)
      td= link_to 'Delete', auction_path(auction), method: :delete, data: {confirm: 'Delete auction, are you sure?'}
      td= link_to 'Start', start_auction_path(auction), method: :patch,
                           data: {confirm: 'Start auction, are you sure? You could not change auction after start'}

app/views/auctions/edit.html.slim
.container
  .row
    .col-md-6.col-md-offset-3
      h1 Edit auction
      h4 Account: #{@auction.account.to_s}
      = simple_form_for @auction, url: auction_path do |f|
        = f.input :final_price, label: 'Price for immediate buy'
        = f.input :minimum_price, label: 'Minimum price'
        = f.input :payment_type, label: 'Payment type', collection: Auction::PAYMENT_TYPES
        = f.input :end_date, label: 'End of auction'
        = f.button :submit, 'Edit auction'

app/views/auctions/index.html.slim
h1 Current auctions
.container
  .row
    .table-responsive
      table.table.table-bordered
        colgroup span="11"
        colgroup span="2"
        thead
          tr
            th colspan="5" scope="colgroup"  Account details
            th colspan="6" scope="colgroup"  Auction details
          tr
            th scope="col" Seller name
            th scope="col" Bookmaker
            th scope="col" Age(months)
            th scope="col" Own account?
            th scope="col" Comment
            th scope="col" Current price - Make bid
            th scope="col" Final price
            th scope="col" Payment type
            th scope="col" End date
            th scope="col" Details
        tbody
          tr
            = render @auctions
    = paginate @auctions, theme: 'twitter-bootstrap-3'
javascript:
    $(document).ready(function () { change_confirmation_of_bid_button_on_index () });

app/views/auctions/manage_auctions.html.slim
h1.center_header Manage auctions
.container
  - if current_user.accounts.opened.any?
    .row
      = link_to new_auction_path do
        .btn.btn-primary.btn-lg
          i.fa.fa-check-square-o
          |  Create auction
  .row
    .table-responsive
      table.table.table-bordered
        thead
          tr
            th Date_added
            th Account
            th Minimum price
            th Current price
            th Final price
            th Payment type
            th End date
            th Comission
            th Status
            th Edit
            th Delete
            th Start auction
        tbody
          tr
            = render 'manage', collection: @auctions

app/views/auctions/new.html.slim
.container
  .row
    .col-md-6.col-md-offset-3
      h1 Create auction
      = simple_form_for @auction, url: auctions_path do |f|
        = f.input :account_id, label: 'Account', collection: @accounts,
                  label_method: :to_s, value_method: :id,
                  selected: @selected_account_id
        = f.input :final_price, label: 'Price for immediate buy'
        = f.input :minimum_price, label: 'Minimum price'
        = f.input :payment_type, label: 'Payment type', collection: Auction::PAYMENT_TYPES
        = f.input :end_date, label: 'End of auction'
        = f.button :submit, 'Add auction'

app/views/auctions/show.html.slim
.container
  .row
    .col-lg-12.center_header
      h1 Auction № #{@auction.id}
      - if @auction.created?
        .row.demobtn
          p
            = link_to 'Start auction', start_auction_path(@auction), method: :patch,
                    data: {confirm: 'Start auction, are you sure? You could not change auction after start'},
                    class: 'btn btn-lg btn-success'
            = link_to 'Edit auction', edit_auction_path(@auction), class: 'btn btn-lg btn-warning'
            = link_to 'Delete auction', auction_path(@auction), method: :delete,
                    data: {confirm: 'Delete auction, are you sure?'},
                    class: 'btn btn-lg btn-danger'
      - if @auction.finished? && @current_winner
        .row.demobtn
          p
            = link_to 'Close auction', close_auction_path(@auction), method: :patch,
                    data: {confirm: 'Close auction, are you sure?'},
                    class: 'btn btn-lg btn-success'

    .col-lg-4
      .pricing-box-alt.special
        .pricing-heading
          h3 Account information
        .pricing-terms
          h4 Bookmaker: #{@auction.account.bookmaker}
        .pricing-content
          ul
            li
              span.bold Age:
              |  #{@auction.account.age}
              |  month(s)
            li
              span.bold Own account:
              - if @auction.account.own?
                |  yes
              - else
                |  no
            li
              span.bold Comment:
              |  #{@auction.account.comment}
            li
              span.bold Seller:
              |  #{@auction.account.user.name}
    .col-lg-4
      .pricing-box-alt.special
        .pricing-heading
          h3 Auction information
        .pricing-terms
          h4 Status: #{@auction.status}
        .pricing-content
          ul
            li
              span.bold End date:
              |  #{date_formatter @auction.end_date}
            li
              span.bold Minimum price:
              |  #{humanized_money_with_symbol @auction.minimum_price}
            li
              span.bold Current price:
              |  #{humanized_money_with_symbol @auction.current_price}
            li
              span.bold Final price:
              |  #{humanized_money_with_symbol @auction.final_price}
            li
              span.bold Payment type:
              |  #{Auction::PAYMENT_TYPES.key(@auction.payment_type)}
        - if @auction.active?
          .pricing-action
            = link_to "Buy immediately for #{humanized_money_with_symbol @auction.final_price}",
                    buy_immediately_auction_path(@auction), method: :patch,
                    class: 'btn btn-theme',
                    data: {confirm: "You will buy this account for #{humanized_money_with_symbol @auction.final_price}. Confirm operation?"}
    .col-lg-4
      .pricing-box-alt.special
        .pricing-heading
          h3 Last bids
        .pricing-terms
          - if @current_winner
            h4 Your bid is the biggest now!
          - else
            h4 Info about 4 last bids
        .pricing-content
          ul
            - @bids.each do |bid|
              li
                span.bold Date:
                |  #{time_formatter bid.created_at}
                span.bold  Stake:
                |   #{humanized_money_with_symbol bid.stake}
        - if @auction.active?
          .pricing-action
            = simple_form_for [@auction, @auction.bids.new] do |f|
              = f.input_field :stake, label: false, value: @auction.current_price,
                      type: :number, min: @auction.current_price
              td
                = f.button :submit, class: 'btn-theme',
                        data: {confirm: 'Do you confirm the stake? This operation could not be canceled'}
  - if @auction.created?
    p
      = link_to 'Start auction', start_auction_path(@auction), method: :patch,
              data: {confirm: 'Start auction, are you sure? You could not change auction after start'},
              class: 'btn btn-lg btn-theme'
  p= link_to 'Return to all auctions list', auctions_path
javascript:
  $(document).ready(function () { change_confirmation_of_bid_button_on_show() });