config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index]

  resources :accounts, only: [:new, :create, :edit, :update, :show, :destroy] do
    collection do
      get :manage_accounts
      get :bought_accounts
    end
  end

  resources :auctions, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
    resources :bids
    collection do
      get :manage_auctions
    end
    member do
      patch :start, :buy_immediately, :close
    end
  end

  get 'about', to: 'home#about'
  root to: 'home#index'

  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/views/layouts/_footer.html.slim
footer
  .container-fluid
    .row
      .col-md-12
        .bg-info
          = debug(params) if Rails.env.development?

app/views/layouts/_head.html.slim
head
  meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
  title UAbets accounts

  = csrf_meta_tags
= stylesheet_link_tag 'application', media: 'all'
= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css', media: 'all'
= javascript_include_tag 'application'

app/views/layouts/_header.html.slim
header
  nav.navbar.navbar-default.navbar-static-top
    .container
      .navbar-header
        button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="/"
          img alt="Uabets accounts" height="45" src="/img/logo.png" width="250"
      .navbar-collapse.collapse
        ul.nav.navbar-nav
          li
            a href="/about" About
          li
            = link_to 'Buy account', auctions_path
          li
            a href="/about" Rules
          li
            a href="/about" Contacts
          - unless current_user
            li
              = link_to('Sign in', new_user_session_path)
            li
              = link_to('Sign up', new_user_registration_path)
          - else
            li.dropdown
              a.dropdown-toggle data-close-others="false" data-delay="0" data-hover="dropdown" data-toggle="dropdown" href="#"
                | My profile
                i.fa.fa-angle-down
              ul.dropdown-menu
                li
                  = link_to 'Add account', new_account_path
                li
                  = link_to 'Manage accounts', manage_accounts_accounts_path
                li
                  = link_to 'Bought accounts', bought_accounts_accounts_path
                li
                  = link_to 'Manage auctions', manage_auctions_auctions_path
                li
                  a href="#"  Payments
                li
                  a href="#"  My settings
                li
                  = link_to('Logout', destroy_user_session_path, method: :delete)

app/views/layouts/application.html.slim
doctype html
html
  = render 'layouts/head'

  body
    = render 'layouts/header'
    main
      .container-fluid
        section
          .unobtrusive-flash-container
          = yield
      #footer
= render 'layouts/footer'