config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index]

  resources :accounts, only: [:new, :create, :edit, :update, :show, :destroy] do
    collection do
      get :manage_accounts
      get :bought_accounts
    end
  end

  resources :auctions, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
    resources :bids
    collection do
      get :manage_auctions
    end
    member do
      patch :start, :buy_immediately, :close
    end
  end

  get 'about', to: 'home#about'
  root to: 'home#index'

  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/account.rb
class Account < ApplicationRecord
  include AASM

  belongs_to :user
  has_many :auctions, dependent: :destroy

  enum status: [:opened, :auction, :sold]

  validates :bookmaker, :age, presence: true
  validates :bookmaker, inclusion: { in: Appvalues['bookmaker'] }
  validates :age, inclusion: { in: 1..180 }
  validates :comment, length: { maximum: 1000 }

  scope :bought, ->(a) { where(buyer_id: a) }
  scope :opened, -> { where(status: :opened) }

  aasm column: :status, enum: true do
    state :opened, initial: true
    state :auction, :sold

    event :create_auction do
      transitions from: :opened, to: :auction
    end

    event :delete_auction do
      transitions from: :auction, to: :opened
    end

    event :complete_auction do
      transitions from: :auction, to: :sold
    end
  end

  def to_s
    "#{id} : #{created_at.strftime('%m.%d.%Y, %H:%M')} : #{bookmaker}"
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :find_account, only: [:show, :edit, :update, :destroy]
  before_action :check_opened, only: [:edit, :update, :destroy]

  def show; end

  def new
    @account = current_user.accounts.new
  end

  def create
    @account = current_user.accounts.new(account_params)
    if @account.save
      redirect_to manage_accounts_accounts_path, notice: 'Account was created!'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @account.update_attributes(account_params)
      flash[:success] = 'Account updated'
      redirect_to manage_accounts_accounts_path
    else
      render 'edit'
    end
  end

  def destroy
    @account.destroy
    flash[:notice] = 'Account was deleted'
    redirect_back(fallback_location: root_path)
  end

  def manage_accounts
    @accounts = current_user.accounts.page(params[:page]).per(5)
  end

  def bought_accounts
    @bought_accounts = Account.bought(current_user.id).page(params[:page])
                           .per(5)
  end

  private

  def account_params
    params.require(:account).permit(:bookmaker, :age,
                                    :own, :comment)
  end

  def find_account
    @account = Account.find(params[:id])
    return if @account.user == current_user
    redirect_to root_path, alert: 'Access denied!'
  end

  def check_opened
    return if @account.opened?
    redirect_to manage_accounts_accounts_path,
                alert: 'You can not change account'
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.slim
tr
  td= account.id
  td= account.created_at
  td= account.bookmaker
  td= account.age
  td= account.own
  td= account.comment
  td= account.status
  - if account.opened?
    td= link_to 'Edit', edit_account_path(account)
    td= link_to 'Delete', account_path(account), method: :delete, data: {confirm: 'Delete account, are you sure?'}
    td= link_to 'Create auction', new_auction_path(selected_account: account.id)

app/views/accounts/_bought_account.html.slim
- @bought_accounts.each do |bought_account|
  tr
    td= bought_account.id
    td= time_formatter bought_account.created_at
    td= bought_account.bookmaker
    td= bought_account.age
    td= bought_account.own
    td= bought_account.comment
    td= humanized_money_with_symbol bought_account.auctions.last.current_price
    td= bought_account.user.name

app/views/accounts/bought_accounts.html.slim
h3.center_header Bought accounts
.container
  .table-responsive
    table.table.table-bordered
      thead
        tr
          th Account ID
          th Date_added
          th Bookmaker
          th Age
          th Own?
          th Comment
          th Price
          th Seller name
      tbody
        tr
          = render 'bought_account', collection: @bought_accounts
  = paginate @bought_accounts, theme: 'twitter-bootstrap-3'

app/views/accounts/edit.html.slim
.container
  .row
    .col-md-6.col-md-offset-3
      h1 Edit account
      = simple_form_for @account, url: account_path do |f|
        = f.input :bookmaker, label: 'Bookmaker', collection: Appvalues['bookmaker']
        = f.input :age, label: 'Account age (in months)'
        = f.input :own, label: 'Is it your own account?'
        = f.input :comment, label: 'Additional information about account'
        = f.button :submit, 'Edit account'

app/views/accounts/manage_accounts.html.slim
h1.center_header Manage accounts
.container
  .row
    = link_to new_account_path do
      .btn.btn-primary.btn-lg
        i.fa.fa-check-square-o
        |  Create account
h3.center_header Added accounts
.container
  .table-responsive
    table.table.table-bordered
      thead
        tr
          th Account ID
          th Date_added
          th Bookmaker
          th Age
          th Own?
          th Comment
          th Status
          th Edit
          th Delete
          th Create auction
      tbody
        tr
          = render @accounts
  = paginate @accounts, theme: 'twitter-bootstrap-3'

app/views/accounts/new.html.slim
h1 Create account
= simple_form_for @account, url: accounts_path do |f|
  = f.input :bookmaker, label: 'Bookmaker', collection: Appvalues['bookmaker']
  = f.input :age, label: 'Account age'
  = f.input :own, label: 'Is it your own account?'
  = f.input :comment, label: 'Additional information about account'
  = f.button :submit, 'Add account'

app/views/accounts/show.html.slim
h1 Account № #{@account.id}
p Bookmaker: #{@account.bookmaker}
p Age: #{@account.age}
p Comment: #{@account.comment}
p User: #{@account.user.name}
p= link_to 'Manage your accounts', manage_accounts_accounts_path